[toolchain]
channel = "1.75.0"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
msc_contracts = "DaSw2ffsW6C78ZKDwjMFPDt7mRLttjUymgbAAnwsaF9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgrade_authority_off = false
url = "http://localhost:8899"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
